### ISSUE TITLE
Exception printed from router thread even when one is caught by the application

### ISSUE THREAD

**Issue by Jajcus** [selectel/pyxs#8]
Test code:
```python
#!/usr/bin/python3

import pyxs

router = pyxs.Router(pyxs.connection.XenBusConnection())
xs = pyxs.Client(router=router)

try:
    xs.connect()
except pyxs.ConnectionError:
    print("ConnectionError caught")
```

Expected output on non-xen VM:
```
ConnectionError caught
```

Actual output on non-xen VM:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/share/python3.5/site-packages/pyxs/connection.py", line 199, in __init__
    self.fd = os.open(path, os.O_RDWR)
FileNotFoundError: [Errno 2] No such file or directory: '/proc/xen/xenbus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/python3.5/threading.py", line 923, in _bootstrap_inner
    self.run()
  File "/usr/share/python3.5/threading.py", line 871, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/share/python3.5/site-packages/pyxs/client.py", line 101, in __call__
    self.connection.connect()
  File "/usr/share/python3.5/site-packages/pyxs/connection.py", line 52, in connect
    self.transport = self.create_transport()
  File "/usr/share/python3.5/site-packages/pyxs/connection.py", line 245, in create_transport
    return _XenBusTransport(self.path)
  File "/usr/share/python3.5/site-packages/pyxs/connection.py", line 202, in __init__
    .format(path, e.args))
pyxs.exceptions.ConnectionError: error while opening '/proc/xen/xenbus': (2, 'No such file or directory')

ConnectionError caught
```

**Comment by superbobry** [comment]
I've pushed a patch. Could you give a try and let me know if it works for you?

**Comment by Jajcus** [comment]
Yes, it is much better now.
The code seems to work properly both in Xen and non-Xen VM.

**Comment by superbobry** [comment]
Thank you for the feedback, I've uploaded a bugfix release to PyPI.
